# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 09:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import models, migrations

def make_many_artists(apps, schema_editor):
    """
        Adds the Artist object in Artwork.artist to the
        many-to-many relationship in Artwork.artists
    """
    Artwork = apps.get_model('streetart', 'Artwork')

    for artwork in Artwork.objects.all():
        artwork.artists.add(artwork.artist)

class Migration(migrations.Migration):

    replaces = [('streetart', '0001_squashed_0015_auto_20170821_1309'), ('streetart', '0002_auto_20170821_1718'), ('streetart', '0003_auto_20170823_1047'), ('streetart', '0004_auto_20170823_1103'), ('streetart', '0005_remove_artwork_artist'), ('streetart', '0006_auto_20170823_1158'), ('streetart', '0007_auto_20170824_1211'), ('streetart', '0008_artwork_validated'), ('streetart', '0009_auto_20170828_1433'), ('streetart', '0010_auto_20170828_1447'), ('streetart', '0011_remove_alternativeimage_photo_credit'), ('streetart', '0012_auto_20170828_1627'), ('streetart', '0013_artistexpressionofinterest_muralcommission_wallspace'), ('streetart', '0014_auto_20170829_0830'), ('streetart', '0015_auto_20170829_0830'), ('streetart', '0016_auto_20170829_1335'), ('streetart', '0017_route_routepoint'), ('streetart', '0018_auto_20170829_1441'), ('streetart', '0019_auto_20170829_1526'), ('streetart', '0020_auto_20170829_1529'), ('streetart', '0021_auto_20170830_1312'), ('streetart', '0022_auto_20170830_1313'), ('streetart', '0023_auto_20170830_1539'), ('streetart', '0024_auto_20170830_1920')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('artist_from', models.CharField(max_length=200)),
                ('other_links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('commission_date', models.DateTimeField(verbose_name='date commissioned')),
                ('status', models.CharField(max_length=200)),
                ('decommission_date', models.DateTimeField(verbose_name='date decommissioned')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='artwork/')),
                ('photo_credit', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='artwork_thumbnails/')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetart.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('is_disbanded', models.BooleanField()),
                ('formed_date', models.DateTimeField(verbose_name='date formed')),
                ('disband_date', models.DateTimeField(blank=True, null=True, verbose_name='date disbanded')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streetart.Artwork_Category'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streetart.Crew'),
        ),
        migrations.AddField(
            model_name='artist',
            name='crews',
            field=models.ManyToManyField(to='streetart.Crew'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='other_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='decommission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date decommissioned'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='commission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date commissioned'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='artwork/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streetart.Artist'),
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streetart.Artist'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='streetart.Artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='streetart.Artist'),
        ),
        migrations.RunPython(make_many_artists),
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='commission_date',
            field=models.DateField(blank=True, null=True, verbose_name='date commissioned'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='decommission_date',
            field=models.DateField(blank=True, null=True, verbose_name='date decommissioned'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streetart.Status'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='artwork/')),
                ('photo_credit', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='streetart.Artwork'),
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='AlternativeImage',
        ),
        migrations.RemoveField(
            model_name='alternativeimage',
            name='photo_credit',
        ),
        migrations.AddField(
            model_name='artwork',
            name='checkins',
            field=models.ManyToManyField(blank=True, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(default='defaultslug'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ArtistExpressionOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MuralCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WallSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.TextField(blank=True, null=True, verbose_name='How big is the wall? Please give us the dimensions of the wall so we can give the artist an idea of how big the space is.')),
                ('email', models.EmailField(default='admin@lab3.co.nz', max_length=254, verbose_name='Email Address')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='wallspace/', verbose_name='If possible please aattach a photo of the wall.')),
                ('wall_location', django.contrib.gis.db.models.fields.PointField(default='', srid=4326, verbose_name='Where is the space?')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Name')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Is there anything else we should know?')),
                ('phone', models.CharField(default='', max_length=15)),
                ('relation', models.TextField(blank=True, null=True, verbose_name='What is your relation to this wall space?')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='streetart.Artwork')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='streetart.Route')),
            ],
        ),
        migrations.AlterModelOptions(
            name='routepoint',
            options={'ordering': ['route_order']},
        ),
        migrations.AddField(
            model_name='routepoint',
            name='route_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterModelOptions(
            name='routepoint',
            options={'ordering': ('route_order',)},
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='route_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='crew',
        ),
        migrations.AddField(
            model_name='artwork',
            name='crews',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='streetart.Crew'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='submitter_description',
            field=models.TextField(blank=True, null=True, verbose_name="Submitter's Description"),
        ),
        migrations.AddField(
            model_name='artwork',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Submitter's Email Address"),
        ),
        migrations.AddField(
            model_name='artwork',
            name='submitter_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Submitter's Name"),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, related_name='artworks', to='streetart.Artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='streetart.Artist'),
        ),
    ]
