# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 09:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0001_squashed_0024_auto_20170830_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallspace',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='wallspace',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='wallspace',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='wallspace',
            name='wall_location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Where is the space?'),
        ),
    ]
