# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0001_squashed_0015_auto_20170821_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streetart.Artist'),
        ),
    ]
