# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('artist_from', models.CharField(max_length=200)),
                ('other_links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('commission_date', models.DateTimeField(verbose_name='date commissioned')),
                ('status', models.CharField(max_length=200)),
                ('decommission_date', models.DateTimeField(verbose_name='date decommissioned')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='artwork/')),
                ('photo_credit', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='artwork_thumbnails/')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetart.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetart.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('is_disbanded', models.BooleanField()),
                ('formed_date', models.DateTimeField(verbose_name='date formed')),
                ('disband_date', models.DateTimeField(verbose_name='date disbanded')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetart.Artwork_Category'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetart.Crew'),
        ),
        migrations.AddField(
            model_name='artist',
            name='crews',
            field=models.ManyToManyField(to='streetart.Crew'),
        ),
        migrations.AddField(
            model_name='artist',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetart.Question'),
        ),
    ]
