# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0002_auto_20170821_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='streetart.Artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='streetart.Artist'),
        ),
    ]
