# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 10:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0002_auto_20170830_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muralcommission',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='muralcommission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='muralcommission',
            name='title',
        ),
        migrations.AddField(
            model_name='muralcommission',
            name='budget',
            field=models.TextField(blank=True, null=True, verbose_name='Do you have a budget? Roughly how much have you put aside for the art work?'),
        ),
        migrations.AddField(
            model_name='muralcommission',
            name='deadline',
            field=models.TextField(blank=True, null=True, verbose_name='Does this project have a deadline?'),
        ),
        migrations.AddField(
            model_name='muralcommission',
            name='dimensions',
            field=models.TextField(blank=True, null=True, verbose_name='How big is the wall? Please give us the dimensions of the wall so we can give the artist an idea of how big the space is.'),
        ),
        migrations.AddField(
            model_name='muralcommission',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muralcommission',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='muralcommission/', verbose_name='If possible please attach a photo of the wall.'),
        ),
        migrations.AddField(
            model_name='muralcommission',
            name='mural_location',
            field=django.contrib.gis.db.models.fields.PointField(default='', srid=4326, verbose_name='Where will the mural be?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muralcommission',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muralcommission',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='Is there anything else we should know that will help us to connect you up with the right artist?'),
        ),
        migrations.AddField(
            model_name='muralcommission',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muralcommission',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Most artists prefer to have creative freedom when creating their works, but could you give us an idea of what you are commissioning the mural for or what you hope to see in it? This will help us figure out which artists to get you in contact with.'),
        ),
        migrations.AlterField(
            model_name='wallspace',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='wallspace/', verbose_name='If possible please attach a photo of the wall.'),
        ),
    ]
