# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0002_auto_20170810_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='question',
        ),
    ]
