# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0003_auto_20170830_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistexpressionofinterest',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='artistexpressionofinterest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artistexpressionofinterest',
            name='title',
        ),
        migrations.AddField(
            model_name='artistexpressionofinterest',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistexpressionofinterest',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Are you located in Christchurch? If not, where are you from?'),
        ),
        migrations.AddField(
            model_name='artistexpressionofinterest',
            name='materials',
            field=models.TextField(blank=True, null=True, verbose_name='Would you be able to organize your own materials? What supplies do you require us to organize for you?'),
        ),
        migrations.AddField(
            model_name='artistexpressionofinterest',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistexpressionofinterest',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name="Is there anything you'd like us to know?"),
        ),
        migrations.AddField(
            model_name='artistexpressionofinterest',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistexpressionofinterest',
            name='project_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Paid commisionings'), (2, 'I would consider unpaid opportunities or less than market rate. I am more interested in building my portfolio and giving back to the community.'), (3, 'Mentoring and teaching opportunties. Working with up and coming artists or students.')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistexpressionofinterest',
            name='samples',
            field=models.TextField(blank=True, null=True, verbose_name='Please provide samples of past work or include a link to your website or portfolio.'),
        ),
        migrations.AddField(
            model_name='artistexpressionofinterest',
            name='why',
            field=models.TextField(blank=True, null=True, verbose_name='Why do you want to create work here in Christchurch?'),
        ),
    ]
