# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 23:03
from __future__ import unicode_literals

from django.db import models, migrations

def make_many_artists(apps, schema_editor):
    """
        Adds the Artist object in Artwork.artist to the
        many-to-many relationship in Artwork.artists
    """
    Artwork = apps.get_model('streetart', 'Artwork')

    for artwork in Artwork.objects.all():
        artwork.artists.add(artwork.artist)

class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0003_auto_20170823_1047'),
    ]

    operations = [
    	migrations.RunPython(make_many_artists),
    ]
