# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0004_auto_20170823_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
    ]
