# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-02 02:32
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0005_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='artwork/'),
        ),
    ]
