# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0005_auto_20170814_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='crews',
            field=models.ManyToManyField(to='streetart.Crew'),
        ),
    ]
