# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0005_remove_artwork_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='commission_date',
            field=models.DateField(blank=True, null=True, verbose_name='date commissioned'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='decommission_date',
            field=models.DateField(blank=True, null=True, verbose_name='date decommissioned'),
        ),
    ]
