# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-02 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0007_auto_20170902_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
