# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0007_auto_20170824_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
