# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0008_artwork_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='artwork/')),
                ('photo_credit', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_images', to='streetart.Artwork'),
        ),
    ]
