# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 23:23
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0009_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '250x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
