# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0009_auto_20170828_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='AlternativeImage',
        ),
    ]
