# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0010_auto_20170828_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativeimage',
            name='photo_credit',
        ),
    ]
