# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0010_artwork_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeimage',
            name='image',
            field=models.ImageField(upload_to='artwork/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '250x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to='artwork/'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='muralcommission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='muralcommission/', verbose_name='If possible please attach a photo of the wall.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/'),
        ),
        migrations.AlterField(
            model_name='wallspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wallspace/', verbose_name='If possible please attach a photo of the wall.'),
        ),
    ]
