# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 04:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streetart', '0011_remove_alternativeimage_photo_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='checkins',
            field=models.ManyToManyField(related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(default='defaultslug'),
            preserve_default=False,
        ),
    ]
