# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 23:52
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0011_auto_20170908_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='cropped_image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='artwork/cropped'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '10000x10000', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='artwork/'),
        ),
    ]
