# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0012_auto_20170828_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistExpressionOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('contact', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MuralCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('contact', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WallSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('contact', models.TextField(max_length=200)),
            ],
        ),
    ]
