# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0012_auto_20170817_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streetart.Artwork_Category'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='commission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date commissioned'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='artwork/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='location',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
