# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0013_auto_20170818_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streetart.Artist'),
        ),
    ]
