# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 01:25
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0013_auto_20170911_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='cropped_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, editable=False, null=True, upload_to='artwork/cropped/'),
        ),
    ]
