# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 01:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0014_auto_20170818_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
