# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0014_auto_20170829_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muralcommission',
            name='contact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='muralcommission',
            name='description',
            field=models.TextField(),
        ),
    ]
