# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0014_auto_20170911_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeimage',
            name='image',
            field=models.ImageField(upload_to='artwork/alternate/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='cropped_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='artwork/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '250x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
