# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 01:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0015_auto_20170829_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='checkins',
            field=models.ManyToManyField(blank=True, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
