# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0016_auto_20170829_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='streetart.Artwork')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='streetart.Route')),
            ],
        ),
    ]
