# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0017_auto_20170911_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
