# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0017_route_routepoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routepoint',
            options={'ordering': ['route_order']},
        ),
        migrations.AddField(
            model_name='routepoint',
            name='route_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
