# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0018_artist_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
