# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0018_auto_20170829_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routepoint',
            options={'ordering': ('route_order',)},
        ),
    ]
