# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0019_auto_20170829_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepoint',
            name='route_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
