# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0020_manual_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
