# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0020_auto_20170829_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='crew',
        ),
        migrations.AddField(
            model_name='artwork',
            name='crews',
            field=models.ManyToManyField(blank=True, null=True, related_name='artworks', to='streetart.Crew'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='submitter_description',
            field=models.TextField(blank=True, null=True, verbose_name="Submitter's Description"),
        ),
        migrations.AddField(
            model_name='artwork',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Submitter's Email Address"),
        ),
        migrations.AddField(
            model_name='artwork',
            name='submitter_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Submitter's Name"),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, related_name='artworks', to='streetart.Artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
