# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0021_auto_20170830_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='streetart.Artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='crews',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='streetart.Crew'),
        ),
    ]
