# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0021_auto_20170914_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Write any notes about the artwork here (will not be shown on map)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='map_enabled',
            field=models.BooleanField(default=True, verbose_name='Show this artwork on the map'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='smart_cities',
            field=models.BooleanField(default=True, verbose_name='Allow this artwork to be accessed by smartcities'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What street is the artwork on (to help in identifying)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='commission_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='date commissioned'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='decommission_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='date decommissioned'),
        ),
    ]
