# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0022_auto_20170914_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='crews',
            field=models.ManyToManyField(null=True, to='streetart.Crew'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='cropped_image',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to='artwork/'),
        ),
    ]
