# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0023_auto_20170917_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='crews',
            field=models.ManyToManyField(blank=True, to='streetart.Crew'),
        ),
    ]
