# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0025_auto_20170917_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='artwork/alternate/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='cropped_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='artwork/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(max_length=500, upload_to='artwork/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='muralcommission',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='muralcommission/', verbose_name='If possible please attach a photo of the wall.'),
        ),
        migrations.AlterField(
            model_name='wallspace',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='wallspace/', verbose_name='If possible please attach a photo of the wall.'),
        ),
    ]
