# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0026_whatsnew'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='GetInvolved',
        ),
    ]
