# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0026_auto_20170919_0845'),
        ('streetart', '0027_auto_20170918_1620'),
    ]

    operations = [
    ]
