# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-08 20:56
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0028_merge_20170919_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistexpressionofinterest',
            name='project_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Paid commisionings'), (2, 'I would consider unpaid opportunities or less than market rate. I am more interested in building my portfolio and giving back to the community.'), (3, 'Mentoring and teaching opportunties. Working with up and coming artists or students.')], max_length=5, null=True),
        ),
    ]
