# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-03 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0030_artwork_watermark_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '404x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('Viewable', 'Viewable'), ('Partially-Viewable', 'Partially-Viewable'), ('Not Viewable', 'Not Viewable'), ('No Data', 'No Data')], max_length=200),
        ),
    ]
