# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-29 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0031_auto_20171128_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_content',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
