# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0035_artwork_watermark_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativeimage',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
