# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-10 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0036_alternativeimage_photo_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='streetart.Status'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('Viewable', 'Viewable'), ('Partially-Viewable', 'Partially-Viewable'), ('Not Viewable', 'Not Viewable'), ('', 'No Data')], default=('', 'No Data'), max_length=200),
        ),
    ]
