# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-26 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0036_alternativeimage_photo_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15)),
                ('feedback', models.TextField(blank=True, verbose_name='Please send us your feedback.')),
            ],
        ),
        migrations.AddField(
            model_name='alternativeimage',
            name='photo_credit_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Photo Credit's Email Address"),
        ),
        migrations.AddField(
            model_name='artwork',
            name='photo_credit_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Photo Credit's Email Address"),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
