# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0037_auto_20171211_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('category', models.CharField(choices=[('I found a bug in website', 'I found a bug in website'), ('Report an Artwork', 'Report an Artwork'), ('Others', 'Others')], max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='streetart.Status'),
        ),
    ]
