# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0040_auto_20201014_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='video',
        ),
        migrations.AddField(
            model_name='artwork',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
