# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-13 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0042_artwork_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='video',
        ),
    ]
