# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-14 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0044_featuredvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredvideo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
