# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetart', '0046_auto_20201015_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredvideo',
            name='thumbnail_image',
            field=models.ImageField(default=None, max_length=500, upload_to='video_tumbnails/'),
            preserve_default=False,
        ),
    ]
